IA.Reclutamiento.ApiTestNGM/IA.Reclutamiento.ApiTestNGM/Controllers/PositionController.cs
using IA.LogicaNegocio.Entities;
using IA.Reclutamiento.ApiTestNGM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IA.Reclutamiento.ApiTestNGM.Controllers
{
    public class PositionController : Controller
    {
        // GET: Position
        public ActionResult Index(string dsearch)
        {
            PositionModel model = new Models.PositionModel();
            Cat_PositionCollection lstResult = new Cat_PositionCollection();

            // Obtener registro de la entidad estatus que corresponde a estatus ACTIVO
            Cat_Status entStatus = new Cat_Status()
            {
                Status_Status = "ACTIVO"
            };
            entStatus = entStatus.GetFirtByData();

            if (entStatus != null)
            {
                // Obtener registros que tengan estatus ACTIVO
                Cat_Position entObj = new Cat_Position()
                {
                    Psotion_StatusId = entStatus.StatusId
                };
                Cat_PositionCollection lstObj = entObj.GetCollectionByData();

                if (String.IsNullOrEmpty(dsearch))
                {
                    model.lstPosition = lstObj;
                }
                // Si se recibe valor de busqueda
                else
                {
                    foreach (Cat_Position objEnt in lstObj)
                    {
                        if (Utilities.General.Contains(objEnt.Position_Description, dsearch, StringComparison.CurrentCultureIgnoreCase))
                        {
                            lstResult.Add(objEnt);
                        }
                    }

                    model.lstPosition = lstResult;
                    model.dsearch = dsearch;
                }
            }

            return View(model);
        }
    }
}

IA.Reclutamiento.ApiTestNGM/IA.Reclutamiento.ApiTestNGM/Controllers/StatusController.cs
using IA.LogicaNegocio.Entities;
using IA.Reclutamiento.ApiTestNGM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IA.Reclutamiento.ApiTestNGM.Controllers
{
    public class StatusController : Controller
    {
        // GET: Status
        public ActionResult Index(string dsearch)
        {
            StatusModel model = new Models.StatusModel();
            Cat_StatusCollection lstResult = new Cat_StatusCollection();

            if (String.IsNullOrEmpty(dsearch))
            {
                model.lstStatus = Cat_Status.GetAll();
            }
            // Si se recibe valor de busqueda
            else
            {
                foreach (Cat_Status objEnt in Cat_Status.GetAll())
                {
                    if (Utilities.General.Contains(objEnt.Status_Status, dsearch, StringComparison.CurrentCultureIgnoreCase))
                    {
                        lstResult.Add(objEnt);
                    }
                }

                model.lstStatus = lstResult;
                model.dsearch = dsearch;
            }

            return View(model);
        }
    }
}

IA.Reclutamiento.ApiTestNGM/IA.Reclutamiento.ApiTestNGM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/js/form-validation.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Cátalogos
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Puestos", "Index", "Position")</li>
                            <li>@Html.ActionLink("Estatus", "Index", "Status")</li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>